name: PAHO web crawling on Github Action
on:
  workflow_dispatch:
  schedule:
    - cron: '00 08 * * *' # 08:00 am UTC every day

jobs:
  Scraping_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'
      - name: Install Google Chrome Stable # STEP 1: Install Chrome
        run: |
          sudo apt-get update -y
          sudo apt-get install -y google-chrome-stable
          google-chrome-stable --version # Verify installation

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          pip install undetected_chromedriver
          pip install setuptools
          pip install webdriver_manager

      - name: Create data directory
        run: mkdir -p ${{ github.workspace }}/data

      - name: Running the Python script
        run: python scripts/PAHOCrawler_UCver_v5.py

      - name: Debug - Check what files were created
        run: |
          echo "Contents of data directory:"
          find ${{ github.workspace }}/data -type f -name "*.csv" | head -10
          echo "Total CSV files in data directory:"
          find ${{ github.workspace }}/data -type f -name "*.csv" | wc -l
          echo "Directory structure:"
          ls -la ${{ github.workspace }}/data/

      - name: Upload debug screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshots
          path: ./debug_*.png
          if-no-files-found: ignore

      - name: Clean up temp downloads
        if: always()
        run: rm -rf temp_downloads/

      - name: Commit CSV files (on success)
        if: success()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Check if there are any CSV changes to commit
          if [[ `git status --porcelain` ]]; then
            echo "Success: Committing CSV files only..."
            git status

            # Add only CSV files and data directories
            git add -A data/

            timestamp=$(date -u)
            git commit -m "Latest data: ${timestamp}"
            git push
          else
            echo "No CSV changes to commit"
          fi

      - name: Commit debug screenshots (on failure)
        if: failure()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Check if there are debug screenshots to commit
          if ls debug_*.png 1> /dev/null 2>&1; then
            echo "Failure: Committing debug screenshots for troubleshooting..."
            git status

            # Add only debug screenshots
            git add debug_*.png

            timestamp=$(date -u)
            git commit -m "Debug screenshots from failed run: ${timestamp}"
            git push
          else
            echo "No debug screenshots to commit"
          fi

      - name: Clean up debug screenshots (don't leave them around)
        if: always()
        run: rm -f debug_*.png
