- name: Create data directory
  run: mkdir -p ${{ github.workspace }}/data

- name: Running the Python script
  run: python scripts/PAHOCrawler_UCver_v5.py

- name: Debug - Check what files were created
  run: |
    echo "Contents of data directory:"
    find ${{ github.workspace }}/data -type f -name "*.csv" | head -10
    echo "Total CSV files in data directory:"
    find ${{ github.workspace }}/data -type f -name "*.csv" | wc -l
    echo "Directory structure:"
    ls -la ${{ github.workspace }}/data/

- name: Upload debug screenshots
  if: failure()
  uses: actions/upload-artifact@v4
  with:
    name: debug-screenshots
    path: ./debug_*.png
    if-no-files-found: ignore

- name: Clean up temp downloads
  if: always()
  run: rm -rf temp_downloads/

- name: Clean up debug screenshots (don't commit them)
  if: always()
  run: rm -f debug_*.png

- name: Commit and Push
  run: |
    git config --global user.name "github-actions[bot]"
    git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    # Check if there are any changes to commit
    if [[ `git status --porcelain` ]]; then
      echo "Changes detected, committing..."
      git status
      git add data/
      timestamp=$(date -u)
      git commit -m "Latest data: ${timestamp}"
      git push
    else
      echo "No changes to commit"
    fi
